eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8082/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
      