eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
zuul:
  routes:
    discovery-server:
      path: /discovery-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8082/eureka/